export const bankData = [
  {
    codigo: "",
    nombre: "Selecionar Banco",
  },
  {
    codigo: "0102",
    nombre: "Banco de Venezuela S.A.C.A. Banco Universal",
    rif: "G200099976",
  },
  {
    codigo: "0104",
    nombre: "Venezolano de Crédito, S.A. Banco Universal",
    rif: "J000029709",
  },
  {
    codigo: "0105",
    nombre: "Banco Mercantil, C.A. Banco Universal",
    rif: "J000029610",
  },
  {
    codigo: "0108",
    nombre: "Banco Provincial, S.A. Banco Universal",
    rif: "J000029679",
  },
  {
    codigo: "0114",
    nombre: "Bancaribe C.A. Banco Universal",
    rif: "J000029490",
  },
  {
    codigo: "0115",
    nombre: "Banco Exterior C.A. Banco Universal",
    rif: "J000029504",
  },
  {
    codigo: "0116",
    nombre: "Banco Occidental de Descuento, Banco Universal C.A",
    rif: "J300619460",
  },
  {
    codigo: "0128",
    nombre: "Banco Caroní C.A. Banco Universal",
    rif: "J095048551",
  },
  {
    codigo: "0134",
    nombre: "Banesco Banco Universal S.A.C.A.",
    rif: "J070133805",
  },
  {
    codigo: "0137",
    nombre: "Banco Sofitasa, Banco Universal",
    rif: "J090283846",
  },
  {
    codigo: "0138",
    nombre: "Banco Plaza, Banco Universal",
    rif: "J002970553",
  },
  {
    codigo: "0146",
    nombre: "Banco de la Gente Emprendedora C.A",
    rif: "J301442040",
  },
  {
    codigo: "0151",
    nombre: "BFC Banco Fondo Común C.A. Banco Universal",
    rif: "J000723060",
  },
  {
    codigo: "0156",
    nombre: "100% Banco, Banco Universal C.A.",
    rif: "J085007768",
  },
  {
    codigo: "0157",
    nombre: "DelSur Banco Universal C.A.",
    rif: "J000797234",
  },
  {
    codigo: "0163",
    nombre: "Banco del Tesoro, C.A. Banco Universal",
    rif: "G200051876",
  },
  {
    codigo: "0166",
    nombre: "Banco Agrícola de Venezuela, C.A. Banco Universal",
    rif: "G200057955",
  },
  {
    codigo: "0168",
    nombre: "Bancrecer, S.A. Banco Microfinanciero",
    rif: "J316374173",
  },
  {
    codigo: "0169",
    nombre: "Mi Banco, Banco Microfinanciero C.A.",
    rif: "J315941023",
  },
  {
    codigo: "0171",
    nombre: "Banco Activo, Banco Universal",
    rif: "J080066227",
  },
  {
    codigo: "0172",
    nombre: "Bancamica, Banco Microfinanciero C.A.",
    rif: "J316287599",
  },
  {
    codigo: "0173",
    nombre: "Banco Internacional de Desarrollo, C.A. Banco Universal",
    rif: "J294640109",
  },
  {
    codigo: "0174",
    nombre: "Banplus Banco Universal, C.A",
    rif: "J000423032",
  },
  {
    codigo: "0175",
    nombre:
      "Banco Bicentenario del Pueblo de la Clase Obrera, Mujer y Comunas B.U.",
    rif: "G200091487",
  },
  {
    codigo: "0176",
    nombre: "Novo Banco, S.A. Sucursal Venezuela Banco Universal",
    rif: "J308918644",
  },
  {
    codigo: "0177",
    nombre: "Banco de la Fuerza Armada Nacional Bolivariana, B.U.",
    rif: "G200106573",
  },
  {
    codigo: "0190",
    nombre: "Citibank N.A.",
    rif: "J000526621",
  },
  {
    codigo: "0191",
    nombre: "Banco Nacional de Crédito, C.A. Banco Universal",
    rif: "J309841327",
  },
  {
    codigo: "0601",
    nombre: "Instituto Municipal de Crédito Popular",
    rif: "G200068973",
  },
];
export const bankData2 = [
  {
    codigo: "",
    nombre: "Selecionar Banco",
  },
  {
    codigo: "0102",
    nombre: "Banco Venezuela  --     Cuenta Nro: 0102-0127-6200-0002-7850",
  },
  {
    codigo: "0105",
    nombre: "Banco Mercantil  --     Cuenta Nro: 0105-0033-8710-3339-8373 ",
  },
  {
    codigo: "0134",
    nombre: "BANESCO          --     Cuenta Nro: 0134-0059-8905-9101-3942",
  },
  {
    codigo: "0171",
    nombre: "Banco Activo     --     Cuenta Nro: 0171-0101-3560-0032-8848",
  },
  {
    codigo: "0175",
    nombre: "BICENTENARIO     --     Cuenta Nro: 0175-0044-9500-7172-0807 ",
  },
];

export const ExchangeRate = [
  { date: "2021-12-01", rate: 4.6322 },
  { date: "2021-12-02", rate: 4.6476 },
  { date: "2021-12-03", rate: 4.638 },
  { date: "2021-12-06", rate: 4.6333 },
  { date: "2021-12-07", rate: 4.6282 },
  { date: "2021-12-08", rate: 4.6379 },
  { date: "2021-12-09", rate: 4.6353 },
  { date: "2021-12-10", rate: 4.6382 },
  { date: "2021-12-14", rate: 4.6212 },
  { date: "2021-12-15", rate: 4.6071 },
];

export const divisas = {
  calls: 4,
  success: true,
  n: 40,
  date: 1639906961,
  "date-format": "19-12-2021 09:42 am",
  "date-utc": "UTC-4",
  currency: "USD",
  country: "Venezuela",
  "country-code": "VE",
  "country-currency": "VES",
  data: [
    {
      id: "promedio",
      name: "Dólar EM",
      type: "principal",
      origin: "https://exchangemonitor.net/dolar-promedio-venezuela",
      icon: "https://exchangemonitor.net/img/ve/exchangemonitor.webp",
      data: {
        date: 1639921251,
        rate: 4.6114,
        last: 4.6089,
        change: 0.0025,
        percent: 0.054243,
      },
      format: {
        date: "19-12-2021 09:40 am",
        rate: "Bs. 4,61",
        last: "Bs. 4,61",
        change: "Bs. 0,00",
        percent: "0,05%",
      },
    },
    {
      id: "monitor-dolar",
      name: "Monitor Dolar Venezuela",
      type: "principal",
      origin: "https://exchangemonitor.net/monitor-dolar-venezuela",
      icon: "https://exchangemonitor.net/img/ve/monitor-dolar.webp",
      data: {
        date: 1639921251,
        rate: 4.5806,
        last: 4.5862,
        change: -0.0056,
        percent: -0.1221,
      },
      format: {
        date: "19-12-2021 09:40 am",
        rate: "Bs. 4,58",
        last: "Bs. 4,59",
        change: "Bs. -0,01",
        percent: "-0,12%",
      },
    },
    {
      id: "enparalelovzla",
      name: "EnParaleloVzla",
      type: "principal",
      origin: "https://www.instagram.com/enparalelovzla/",
      icon: "https://exchangemonitor.net/img/ve/monitor-dolar.webp",
      data: {
        date: 1639760403,
        rate: 4.62,
        last: 4.62,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 01:00 pm",
        rate: "Bs. 4,62",
        last: "Bs. 4,62",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "monitor-dolar-vzla",
      name: "Monitor Dolar Vzla",
      type: "principal",
      origin: "https://monitordolarvzla.com/",
      icon: "https://exchangemonitor.net/img/ve/monitor-dolar-vzla.webp",
      data: {
        date: 1639762250,
        rate: 4.67,
        last: 4.67,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 01:30 pm",
        rate: "Bs. 4,67",
        last: "Bs. 4,67",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "petro",
      name: "Petro",
      type: "nacional",
      origin: "https://www.petro.gob.ve/",
      icon: "https://exchangemonitor.net/img/ve/nacional/petro.webp",
      data: {
        date: 1639710160,
        rate: 259.86,
        last: 259.86,
        change: 0,
        percent: 0,
      },
      format: {
        date: "16-12-2021 11:02 pm",
        rate: "Bs. 259,86",
        last: "Bs. 259,86",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "bcv",
      name: "BCV",
      type: "nacional",
      origin: "http://www.bcv.org.ve/",
      icon: "https://exchangemonitor.net/img/ve/nacional/bcv.webp",
      data: {
        date: 1639773012,
        rate: 4.6157,
        last: 4.6157,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 04:30 pm",
        rate: "Bs. 4,62",
        last: "Bs. 4,62",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "airtm",
      name: "AirTM",
      type: "pagina",
      origin: "https://rates.airtm.com/",
      icon: "https://exchangemonitor.net/img/ve/general/airtm.webp",
      data: {
        date: 1639659605,
        rate: 4.76,
        last: 4.76,
        change: 0,
        percent: 0,
      },
      format: {
        date: "16-12-2021 09:00 am",
        rate: "Bs. 4,76",
        last: "Bs. 4,76",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "akb-fintech",
      name: "AKB Fintech",
      type: "pagina",
      origin: "https://akbfintech.com/",
      icon: "https://exchangemonitor.net/img/ve/general/american-kryptos-bank.webp",
      data: {
        date: 1639733108,
        rate: 4.4522,
        last: 4.4522,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 05:25 am",
        rate: "Bs. 4,45",
        last: "Bs. 4,45",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "localbitcoins",
      name: "LocalBitcoins",
      type: "pagina",
      origin: "https://localbitcoins.com/es/",
      icon: "https://exchangemonitor.net/img/ve/general/localbitcoins.webp",
      data: {
        date: 1639921235,
        rate: 4.5277,
        last: 4.5163,
        change: 0.0114,
        percent: 0.2524,
      },
      format: {
        date: "19-12-2021 09:40 am",
        rate: "Bs. 4,53",
        last: "Bs. 4,52",
        change: "Bs. 0,01",
        percent: "0,25%",
      },
    },
    {
      id: "yadio",
      name: "Yadio",
      type: "pagina",
      origin: "https://yadio.io/",
      icon: "https://exchangemonitor.net/img/ve/general/yadio.webp",
      data: {
        date: 1639921246,
        rate: 4.5177,
        last: 4.4912,
        change: 0.0265,
        percent: 0.59,
      },
      format: {
        date: "19-12-2021 09:40 am",
        rate: "Bs. 4,52",
        last: "Bs. 4,49",
        change: "Bs. 0,03",
        percent: "0,59%",
      },
    },
    {
      id: "dolartoday",
      name: "DolarToday",
      type: "pagina",
      origin: "https://dolartoday.com/",
      icon: "https://exchangemonitor.net/img/ve/general/dolartoday.webp",
      data: {
        date: 1639741523,
        rate: 4.71,
        last: 4.71,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 07:45 am",
        rate: "Bs. 4,71",
        last: "Bs. 4,71",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "dolartoday-btc",
      name: "DolarToday (BTC)",
      type: "pagina",
      origin: "https://dolartoday.com/",
      icon: "https://exchangemonitor.net/img/ve/general/dolartoday-btc.webp",
      data: {
        date: 1639655123,
        rate: 4.47,
        last: 4.47,
        change: 0,
        percent: 0,
      },
      format: {
        date: "16-12-2021 07:45 am",
        rate: "Bs. 4,47",
        last: "Bs. 4,47",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "mkambio",
      name: "Mkambio",
      type: "pagina",
      origin: "https://www.instagram.com/mkambio/",
      icon: "https://exchangemonitor.net/img/ve/general/mkambio.webp",
      data: {
        date: 1639672095,
        rate: 4.8,
        last: 4.8,
        change: 0,
        percent: 0,
      },
      format: {
        date: "16-12-2021 12:28 pm",
        rate: "Bs. 4,80",
        last: "Bs. 4,80",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "cambios-rya",
      name: "Cambios R&A",
      type: "pagina",
      origin: "https://www.instagram.com/cambiosrya/",
      icon: "https://exchangemonitor.net/img/ve/general/cambios-rya.webp",
      data: {
        date: 1639757681,
        rate: 4.52,
        last: 4.69,
        change: -0.17,
        percent: -3.6247,
      },
      format: {
        date: "17-12-2021 12:14 pm",
        rate: "Bs. 4,52",
        last: "Bs. 4,69",
        change: "Bs. -0,17",
        percent: "-3,62%",
      },
    },
    {
      id: "monedero-paypal",
      name: "PayPal",
      type: "e-wallet",
      origin: "https://www.paypal.com/ve/home",
      icon: "https://exchangemonitor.net/img/ve/monederos/paypal.webp",
      data: {
        date: 1639921256,
        rate: 3.97,
        last: 3.96,
        change: 0.01,
        percent: 0.2525,
      },
      format: {
        date: "19-12-2021 09:40 am",
        rate: "Bs. 3,97",
        last: "Bs. 3,96",
        change: "Bs. 0,01",
        percent: "0,25%",
      },
    },
    {
      id: "monedero-uphold",
      name: "Uphold",
      type: "e-wallet",
      origin: "https://uphold.com/es/",
      icon: "https://exchangemonitor.net/img/ve/monederos/uphold.webp",
      data: {
        date: 1639910756,
        rate: 4.16,
        last: 4.16,
        change: 0,
        percent: 0,
      },
      format: {
        date: "19-12-2021 06:45 am",
        rate: "Bs. 4,16",
        last: "Bs. 4,16",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "monedero-skrill",
      name: "Skrill",
      type: "e-wallet",
      origin: "https://www.skrill.com/es/",
      icon: "https://exchangemonitor.net/img/ve/monederos/skrill.webp",
      data: {
        date: 1639910157,
        rate: 4.08,
        last: 4.08,
        change: 0,
        percent: 0,
      },
      format: {
        date: "19-12-2021 06:35 am",
        rate: "Bs. 4,08",
        last: "Bs. 4,08",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "monedero-amazon",
      name: "Amazon Gift Card",
      type: "e-wallet",
      origin: "https://www.amazon.es/",
      icon: "https://exchangemonitor.net/img/ve/monederos/amazon.webp",
      data: {
        date: 1639920357,
        rate: 3.84,
        last: 3.84,
        change: 0,
        percent: 0,
      },
      format: {
        date: "19-12-2021 09:25 am",
        rate: "Bs. 3,84",
        last: "Bs. 3,84",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "remesas-zoom",
      name: "Remesas Zoom",
      type: "nacional",
      origin: "https://www.casadecambiozoom.com/",
      icon: "https://exchangemonitor.net/img/ve/nacional/remesas-zoom.webp",
      data: {
        date: 1639717364,
        rate: 4.66,
        last: 4.66,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 01:02 am",
        rate: "Bs. 4,66",
        last: "Bs. 4,66",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "italcambio",
      name: "Italcambio",
      type: "nacional",
      origin: "http://www.italcambio.com/",
      icon: "https://exchangemonitor.net/img/ve/nacional/italcambio.webp",
      data: {
        date: 1639807353,
        rate: 4.6619,
        last: 4.6846,
        change: -0.0227,
        percent: -0.4846,
      },
      format: {
        date: "18-12-2021 02:02 am",
        rate: "Bs. 4,66",
        last: "Bs. 4,68",
        change: "Bs. -0,02",
        percent: "-0,48%",
      },
    },
    {
      id: "banco-bancamiga",
      name: "Bancamiga",
      type: "banco",
      origin: "https://www.bancamiga.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/bancamiga.webp",
      data: {
        date: 1639778412,
        rate: 4.6468,
        last: 4.6468,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 06:00 pm",
        rate: "Bs. 4,65",
        last: "Bs. 4,65",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-bancaribe",
      name: "BanCaribe",
      type: "banco",
      origin: "https://www.bancaribe.com.ve/",
      icon: "https://exchangemonitor.net/img/ve/bancos/bancaribe.webp",
      data: {
        date: 1638304212,
        rate: 4.609,
        last: 4.609,
        change: 0,
        percent: 0,
      },
      format: {
        date: "30-11-2021 04:30 pm",
        rate: "Bs. 4,61",
        last: "Bs. 4,61",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-de-venezuela",
      name: "Banco de Venezuela",
      type: "banco",
      origin: "http://www.bancodevenezuela.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/banco-de-venezuela.webp",
      data: {
        date: 1639168212,
        rate: 4.63,
        last: 4.63,
        change: 0,
        percent: 0,
      },
      format: {
        date: "10-12-2021 04:30 pm",
        rate: "Bs. 4,63",
        last: "Bs. 4,63",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-exterior",
      name: "Banco Exterior",
      type: "banco",
      origin: "http://www.bancoexterior.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/banco-exterior.webp",
      data: {
        date: 1639600212,
        rate: 4.6466,
        last: 4.6466,
        change: 0,
        percent: 0,
      },
      format: {
        date: "15-12-2021 04:30 pm",
        rate: "Bs. 4,65",
        last: "Bs. 4,65",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-plaza",
      name: "Banco Plaza",
      type: "banco",
      origin: "http://www.bancoplaza.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/banco-plaza.webp",
      data: {
        date: 1638820812,
        rate: 4.63,
        last: 4.63,
        change: 0,
        percent: 0,
      },
      format: {
        date: "06-12-2021 04:00 pm",
        rate: "Bs. 4,63",
        last: "Bs. 4,63",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-banplus",
      name: "Banplus",
      type: "banco",
      origin: "http://www.banplus.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/banplus.webp",
      data: {
        date: 1639778412,
        rate: 4.6234,
        last: 4.6234,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 06:00 pm",
        rate: "Bs. 4,62",
        last: "Bs. 4,62",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-nacional-de-credito-bnc",
      name: "BNC",
      type: "banco",
      origin: "http://www.bnc.com.ve/",
      icon: "https://exchangemonitor.net/img/ve/bancos/bnc.webp",
      data: {
        date: 1639684813,
        rate: 4.6408,
        last: 4.6408,
        change: 0,
        percent: 0,
      },
      format: {
        date: "16-12-2021 04:00 pm",
        rate: "Bs. 4,64",
        last: "Bs. 4,64",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-bod",
      name: "BOD",
      type: "banco",
      origin: "http://www.bod.com.ve/",
      icon: "https://exchangemonitor.net/img/ve/bancos/bod.webp",
      data: {
        date: 1630281612,
        rate: 0,
        last: 4.0838,
        change: -4.0838,
        percent: -100,
      },
      format: {
        date: "29-08-2021 08:00 pm",
        rate: "Bs. 0,00",
        last: "Bs. 4,08",
        change: "Bs. -4,08",
        percent: "-100,00%",
      },
    },
    {
      id: "banco-mi-banco",
      name: "Mi Banco",
      type: "banco",
      origin: "http://www.mibanco.com.ve/",
      icon: "https://exchangemonitor.net/img/ve/bancos/mi-banco.webp",
      data: {
        date: 1635976813,
        rate: 0,
        last: 4.1049,
        change: -4.1049,
        percent: -100,
      },
      format: {
        date: "03-11-2021 06:00 pm",
        rate: "Bs. 0,00",
        last: "Bs. 4,10",
        change: "Bs. -4,10",
        percent: "-100,00%",
      },
    },
    {
      id: "banco-activo",
      name: "Banco Activo",
      type: "banco",
      origin: "http://www.bancoactivo.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/banco-activo.webp",
      data: {
        date: 1635652813,
        rate: 0,
        last: 4.0139,
        change: -4.0139,
        percent: -100,
      },
      format: {
        date: "31-10-2021 12:00 am",
        rate: "Bs. 0,00",
        last: "Bs. 4,01",
        change: "Bs. -4,01",
        percent: "-100,00%",
      },
    },
    {
      id: "banco-del-tesoro",
      name: "Banco del Tesoro",
      type: "banco",
      origin: "http://www.bt.gob.ve/",
      icon: "https://exchangemonitor.net/img/ve/bancos/banco-del-tesoro.webp",
      data: {
        date: 1631478612,
        rate: 0,
        last: 4.1066,
        change: -4.1066,
        percent: -100,
      },
      format: {
        date: "12-09-2021 04:30 pm",
        rate: "Bs. 0,00",
        last: "Bs. 4,11",
        change: "Bs. -4,11",
        percent: "-100,00%",
      },
    },
    {
      id: "banco-banesco",
      name: "Banesco",
      type: "banco",
      origin: "https://www.banesco.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/banesco.webp",
      data: {
        date: 1639684813,
        rate: 4.63,
        last: 4.63,
        change: 0,
        percent: 0,
      },
      format: {
        date: "16-12-2021 04:00 pm",
        rate: "Bs. 4,63",
        last: "Bs. 4,63",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-bbva-provincial",
      name: "BBVA Provincial",
      type: "banco",
      origin: "https://www.provincial.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/bbva-provincial.webp",
      data: {
        date: 1639778412,
        rate: 4.6372,
        last: 4.6372,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 06:00 pm",
        rate: "Bs. 4,64",
        last: "Bs. 4,64",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-mercantil",
      name: "Mercantil",
      type: "banco",
      origin: "https://www.mercantilbanco.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/mercantil.webp",
      data: {
        date: 1639778412,
        rate: 4.6322,
        last: 4.6322,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 06:00 pm",
        rate: "Bs. 4,63",
        last: "Bs. 4,63",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-100x100-banco",
      name: "100% Banco",
      type: "banco",
      origin: "http://www.100x100banco.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/100x100-banco.webp",
      data: {
        date: 0,
        rate: 0,
        last: 0,
        change: 0,
        percent: 0,
      },
      format: {
        date: "",
        rate: "Bs. 0,00",
        last: "Bs. 0,00",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-sofitasa",
      name: "Sofitasa",
      type: "banco",
      origin: "http://www.sofitasa.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/sofitasa.webp",
      data: {
        date: 1625594211,
        rate: 0,
        last: 0,
        change: 0,
        percent: 0,
      },
      format: {
        date: "06-07-2021 01:56 pm",
        rate: "Bs. 0,00",
        last: "Bs. 0,00",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-otras-instituciones",
      name: "Otras Instituciones",
      type: "banco",
      origin: "",
      icon: "https://exchangemonitor.net/img/ve/bancos/otras-instituciones.webp",
      data: {
        date: 1639778412,
        rate: 4.6451,
        last: 4.6451,
        change: 0,
        percent: 0,
      },
      format: {
        date: "17-12-2021 06:00 pm",
        rate: "Bs. 4,65",
        last: "Bs. 4,65",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-bicentenario-del-pueblo",
      name: "Bicentenario",
      type: "banco",
      origin: "http://www.bicentenariobu.com/",
      icon: "https://exchangemonitor.net/img/ve/bancos/bicentenario.webp",
      data: {
        date: 1625594211,
        rate: 0,
        last: 0,
        change: 0,
        percent: 0,
      },
      format: {
        date: "06-07-2021 01:56 pm",
        rate: "Bs. 0,00",
        last: "Bs. 0,00",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-citibank",
      name: "Citibank",
      type: "banco",
      origin: "https://www.citibank.com.ve/",
      icon: "https://exchangemonitor.net/img/ve/bancos/citibank.webp",
      data: {
        date: 1625594211,
        rate: 0,
        last: 0,
        change: 0,
        percent: 0,
      },
      format: {
        date: "06-07-2021 01:56 pm",
        rate: "Bs. 0,00",
        last: "Bs. 0,00",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
    {
      id: "banco-bfc-banco-fondo-comun",
      name: "BFC",
      type: "banco",
      origin: "https://www.bfc.com.ve/",
      icon: "https://exchangemonitor.net/img/ve/bancos/bfc.webp",
      data: {
        date: 1625594211,
        rate: 0,
        last: 0,
        change: 0,
        percent: 0,
      },
      format: {
        date: "06-07-2021 01:56 pm",
        rate: "Bs. 0,00",
        last: "Bs. 0,00",
        change: "Bs. 0,00",
        percent: "0,00%",
      },
    },
  ],
};
